// ============================================================
// Collections (Recaudo) Semaphore Card — HTML Content Visual
// Tracks premium retention rate vs. previous-month close.
// Two panels: Current Month vs. Previous Month Close.
// ============================================================

HTML_KPI_Collections =

-- Current month
VAR _cur_collected = CALCULATE( SUM( fact_collections[collected_amount] ), dim_date[is_current_month] = TRUE )
VAR _cur_billed    = CALCULATE( SUM( fact_collections[billed_amount] ),    dim_date[is_current_month] = TRUE )
VAR _cur_rate      = DIVIDE( _cur_collected, _cur_billed, 0 ) * 100

-- Previous month close (cierre mes anterior)
VAR _prev_collected = CALCULATE( SUM( fact_collections[collected_amount] ), dim_date[is_prev_month] = TRUE )
VAR _prev_billed    = CALCULATE( SUM( fact_collections[billed_amount] ),    dim_date[is_prev_month] = TRUE )
VAR _prev_rate      = DIVIDE( _prev_collected, _prev_billed, 0 ) * 100

VAR _delta = _cur_rate - _prev_rate

VAR _color_cur =
    SWITCH( TRUE(),
        _cur_rate >= 90, "#28a745",
        _cur_rate >= 75, "#ffc107",
        "#dc3545"
    )

VAR _arrow =
    IF( _delta >= 0,
        "<span style='color:#28a745'>▲ " & FORMAT( _delta, "0.0" ) & "pp</span>",
        "<span style='color:#dc3545'>▼ " & FORMAT( ABS( _delta ), "0.0" ) & "pp</span>"
    )

RETURN
"<div style='font-family:Segoe UI,sans-serif; display:flex; gap:12px;'>

  <div style='
      flex:1; background:#fff; border-radius:12px;
      border-left:6px solid " & _color_cur & ";
      padding:14px 18px; box-shadow:0 2px 8px rgba(0,0,0,.08);
  '>
    <p style='margin:0;font-size:10px;color:#6c757d;text-transform:uppercase;letter-spacing:.5px;'>Current Month</p>
    <p style='margin:4px 0 6px;font-size:28px;font-weight:700;color:#212529;'>" & FORMAT( _cur_rate / 100, "0.0%" ) & "</p>
    <p style='margin:0;font-size:12px;color:#495057;'>Collections rate " & _arrow & "</p>
  </div>

  <div style='
      flex:1; background:#f8f9fa; border-radius:12px;
      border-left:6px solid #6c757d;
      padding:14px 18px; box-shadow:0 2px 8px rgba(0,0,0,.08);
  '>
    <p style='margin:0;font-size:10px;color:#6c757d;text-transform:uppercase;letter-spacing:.5px;'>Previous Month Close</p>
    <p style='margin:4px 0 6px;font-size:28px;font-weight:700;color:#6c757d;'>" & FORMAT( _prev_rate / 100, "0.0%" ) & "</p>
    <p style='margin:0;font-size:12px;color:#6c757d;'>Final retention rate</p>
  </div>

</div>"
